'use client';
import {downloadText} from '@/lib/download-text';
import {useState} from 'react';
import {Bell,Bookmark,CalendarDays,ExternalLink,Globe2,MapPin,Plus,ShieldCheck,Sun,HeartPulse,Landmark,Activity,BriefcaseBusiness,Check,Send,Users,Compass} from 'lucide-react';
import type {Journey,Profile} from '@/lib/planner';
import {cityEvents,cityResources,filterEvents,eventCalendar,CityEvent} from '@/lib/city';
type Notice={id:string;title:string;body:string;publisher:string;demo:boolean};
export default function CityHub({view,profile}:{view:string;profile:Profile}){
const [category,setCategory]=useState('All'),[scope,setScope]=useState('All locations'),[saved,setSaved]=useState<string[]>([]),[savedOnly,setSavedOnly]=useState(false),[match,setMatch]=useState(false),[resource,setResource]=useState('All'),[read,setRead]=useState<string[]>([]),[follows,setFollows]=useState<string[]>(['Events']),[compose,setCompose]=useState(false),[title,setTitle]=useState(''),[body,setBody]=useState(''),[publisher,setPublisher]=useState('Community organiser'),[demoNotices,setDemoNotices]=useState<Notice[]>([]),[message,setMessage]=useState('');
const notices:Notice[]=[{id:'winter-guide',title:'Your winter discovery guide is ready',body:'Explore culture, sport and seasonal ideas alongside your relocation tasks.',publisher:'Forever Abu Dhabi editorial · curated guide',demo:false},{id:'event-digest',title:'December events to plan around',body:'F1, Finance Week and the Abu Dhabi Marathon have official 2026 listings. Check event pages before making arrangements.',publisher:'Forever Abu Dhabi editorial · official-source digest',demo:false},...demoNotices];
function toggleSave(id:string){setSaved(prev=>prev.includes(id)?prev.filter(x=>x!==id):[...prev,id]);}
function downloadCalendar(e:CityEvent){downloadText(eventCalendar(e),e.id+'.ics','text/calendar;charset=utf-8');setMessage('Calendar reminder downloaded. This does not register you for the event.');}
function addNotice(e:React.FormEvent){e.preventDefault();if(!title.trim()||!body.trim())return;setDemoNotices(prev=>[{id:'demo-'+Date.now(),title:title.trim(),body:body.trim(),publisher:publisher+' · DEMO',demo:true},...prev]);setTitle('');setBody('');setCompose(false);setMessage('Demo notice added for this visit. Nothing was sent to another person.');}
if(view!=='discover'&&view!=='network')return null;
const selected=filterEvents(category,scope,savedOnly,saved,match?profile.journey:undefined);
const priorities:Record<Journey,string[]>={Founder:['Business','Careers','Culture'],Investor:['Property','Markets','Business'],Retiree:['Healthcare','Culture','Fitness'],'Job seeker':['Careers','Fitness','Culture']};
const resources=cityResources.filter(r=>(resource==='All'||r.category===resource)).sort((a,b)=>{const order=(category:string)=>{const i=priorities[profile.journey].indexOf(category);return i<0?99:i;};return order(a.category)-order(b.category);});
return <div className="city-hub">{message&&<div className="feedback notice" role="status"><Check size={17}/>{message}<button aria-label="Dismiss message" onClick={()=>setMessage('')}>×</button></div>}
{view==='discover'?<><section className="city-hero"><div><div className="eyebrow">MAKE THIS CITY YOUR OWN</div><h2>A life beyond the checklist.</h2><p>Culture to discover. Communities to join. Opportunities to explore.</p><span className="city-hero-location"><MapPin size={15}/>Abu Dhabi · UAE</span></div><div className="city-photo" role="img" aria-label="Louvre Abu Dhabi’s patterned dome above the waterfront, with blue water and shoreline greenery in an illustrative edit"><a href="https://visitabudhabi.ae/en/things-to-do/culture/museums-and-art/louvre-abu-dhabi" target="_blank" rel="noreferrer">Illustrative edit · Experience Abu Dhabi source</a></div></section>
<section className="season-card"><span className="season-icon"><Sun size={27}/></span><div><span className="eyebrow">WINTER IS ON THE HORIZON</span><h3>Plan for Abu Dhabi’s outdoor season</h3><p>Experience Abu Dhabi describes December–March as the winter season, with temperatures typically around 15–26°C. These are seasonal ranges, not a live forecast.</p></div><a className="button secondary" href="https://visitabudhabi.ae/en/campaign/winter" target="_blank" rel="noreferrer">Seasonal guide <ExternalLink size={15}/></a></section>
<div className="section-heading city-section-heading"><div><h2>Find your place in Abu Dhabi</h2><p>Prioritized for your {profile.journey.toLowerCase()} journey · Explore all categories.</p></div><label className="filter"><span className="sr-only">Filter discovery resources</span><select value={resource} onChange={e=>setResource(e.target.value)}>{['All','Culture','Fitness','Healthcare','Property','Careers','Business','Markets'].map(x=><option key={x}>{x}</option>)}</select></label></div>
<div className="resource-grid">{resources.map(r=>{const Icon=r.category==='Healthcare'?HeartPulse:r.category==='Fitness'?Activity:r.category==='Culture'?Landmark:r.category==='Property'?MapPin:r.category==='Markets'?Globe2:BriefcaseBusiness;return <article className="resource-card" key={r.id}><div className="resource-card-top"><span className={'resource-icon '+r.category.toLowerCase()}><Icon size={22}/></span><span className="pill">{r.category}</span></div><h3>{r.title}</h3><p>{r.body}</p><span className="resource-source">Source: {r.source}</span><a className="text-button" href={r.url} target="_blank" rel="noreferrer">{r.action}<ExternalLink size={14}/></a></article>})}</div>
<section className="future-data"><Globe2 size={23}/><div><h3>Market data, with its source attached.</h3><p>Official ADX and ADREC pages are available above. Direct market feeds, property listings and price alerts are planned integrations and are not connected to this prototype.</p></div><span className="pill">Future integration</span></section></>:<>
<div className="network-grid"><section className="events-panel"><div className="section-heading"><div><h2>Events worth making room for</h2><p>Curated listings · checked 2 October 2026</p></div><span className="saved-counter"><Bookmark size={15}/>{saved.length} saved</span></div><div className="event-controls"><div className="category-tabs" aria-label="Event categories">{['All','Business','Sport','Culture'].map(c=><button className={category===c?'selected':''} key={c} onClick={()=>setCategory(c)}>{c}</button>)}</div><label className="filter"><span className="sr-only">Event location</span><select value={scope} onChange={e=>setScope(e.target.value)}>{['All locations','Abu Dhabi','Worldwide'].map(s=><option key={s}>{s}</option>)}</select></label></div><div className="event-options"><label><input type="checkbox" checked={savedOnly} onChange={e=>setSavedOnly(e.target.checked)}/>Saved only</label><label><input type="checkbox" checked={match} onChange={e=>setMatch(e.target.checked)}/>Suggested for my journey</label></div>
<div className="events-list">{selected.map(e=><article className="event-card" key={e.id}><div className="event-date"><span>{new Date(e.start+'T12:00:00Z').toLocaleDateString('en-GB',{month:'short',timeZone:'UTC'})}</span><strong>{Number(e.start.slice(-2))}</strong><small>2026</small></div><div className="event-content"><div className="event-tags"><span className={'event-category '+e.category.toLowerCase()}>{e.category}</span><span>{e.scope==='Worldwide'?<Globe2 size={13}/>:<MapPin size={13}/>} {e.scope}</span></div><h3>{e.title}</h3><span className="event-organizer">{e.organizer}</span><p>{e.description}</p><div className="event-location"><CalendarDays size={14}/>{e.dateLabel}<span>·</span>{e.place}</div><div className="event-actions"><a className="button primary small" href={e.url} target="_blank" rel="noreferrer">View organiser page <ExternalLink size={14}/></a><button className="button secondary small" onClick={()=>downloadCalendar(e)}><CalendarDays size={14}/>Add to calendar</button></div></div><button className={'save-event '+(saved.includes(e.id)?'saved':'')} aria-pressed={saved.includes(e.id)} aria-label={(saved.includes(e.id)?'Unsave ':'Save ')+e.title} onClick={()=>toggleSave(e.id)}><Bookmark size={20} fill={saved.includes(e.id)?'currentColor':'none'}/></button></article>)}{!selected.length&&<div className="empty-state"><CalendarDays size={28}/><h3>No curated events match</h3><p>Change the filters or explore the official calendars below.</p></div>}</div><div className="community-links"><a href="https://adsc.gov.ae/events" target="_blank" rel="noreferrer"><Activity size={17}/><span>Sports & community calendar<small>Abu Dhabi Sports Council</small></span><ExternalLink size={14}/></a><a href="https://visitabudhabi.ae/en/campaign/winter/arts-and-culture" target="_blank" rel="noreferrer"><Landmark size={17}/><span>Cultural experiences<small>Experience Abu Dhabi</small></span><ExternalLink size={14}/></a><a href="https://luma.com/" target="_blank" rel="noreferrer"><Globe2 size={17}/><span>Explore global communities<small>Luma · external discovery</small></span><ExternalLink size={14}/></a></div><p className="timeline-note">Saved events and calendar reminders are held for this visit. Registration happens on the organiser’s site.</p></section>
<aside className="network-sidebar"><section className="side-card updates-card"><div className="card-title"><Bell size={18}/><h3>Your updates</h3><span className="count-badge">{notices.filter(n=>!read.includes(n.id)).length}</span></div><p>Editorial updates and clearly marked demo notices.</p><button className="text-button mark-read" onClick={()=>setRead(notices.map(n=>n.id))}>Mark all read</button>{notices.map(n=><article className={'notification '+(read.includes(n.id)?'read':'')} key={n.id}><div className="notification-title"><strong>{n.title}</strong>{!read.includes(n.id)&&<span aria-label="Unread"/>}</div><small>{n.publisher}</small><p>{n.body}</p>{n.demo&&<span className="pill">Demo notice · not an official message</span>}{!read.includes(n.id)&&<button className="text-button" onClick={()=>setRead(prev=>[...prev,n.id])}>Mark read</button>}</article>)}</section>
<section className="side-card"><div className="card-title"><Users size={18}/><h3>Your interests</h3></div><p>Preview which updates you would like to follow. No email or push subscription is created.</p><div className="interest-chips">{['Events','Culture','Fitness','Investment','Careers','Healthcare'].map(f=><button key={f} className={follows.includes(f)?'following':''} aria-pressed={follows.includes(f)} onClick={()=>setFollows(prev=>prev.includes(f)?prev.filter(x=>x!==f):[...prev,f])}>{follows.includes(f)?<Check size={13}/>:<Plus size={13}/>} {f}</button>)}</div></section>
<section className="publisher-card"><div className="card-eyebrow"><ShieldCheck size={17}/>PARTNER PUBLISHING</div><h3>A channel for the city’s ecosystem.</h3><p>Future government and partner connections can publish relevant announcements here. This prototype is not connected to any government notification system.</p><button className="button secondary" onClick={()=>setCompose(!compose)}><Send size={15}/>{compose?'Close preview':'Preview a demo notice'}</button>{compose&&<form className="notice-form" onSubmit={addNotice}><label>Publisher type<select value={publisher} onChange={e=>setPublisher(e.target.value)}><option>Community organiser</option><option>Government partner</option><option>Investor network</option></select></label><label>Title<input required maxLength={100} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Message<textarea required maxLength={500} value={body} onChange={e=>setBody(e.target.value)}/></label><button className="button primary" type="submit">Add demo notice</button><small>For this visit only. No broadcast, submission or verification.</small></form>}</section></aside></div>
</>}<div className="source-note city-note"><ShieldCheck size={18}/><p>Discovery suggestions are curated, not live matches or official endorsements. Check source pages for current details and availability. Government notifications, live market feeds and member-to-member networking are future integrations.</p></div></div>;
}
