'use client';
import {useState} from 'react';
import {Sparkles,Send,LoaderCircle} from 'lucide-react';
import {Profile} from '@/lib/planner';
import {guidedReply} from '@/lib/guided-assistant';
type Message={role:'user'|'assistant';content:string;mode?:'AI'|'Guided planner'};
function ReplyText({text}:{text:string}){return <p>{text.split(/(https?:\/\/[^\s]+)/g).map((part,i)=>/^https?:\/\//.test(part)?<a key={i} href={part} target="_blank" rel="noopener noreferrer">{part}</a>:part)}</p>;}
export default function PersonalAssistant({profile,done,available,onReviewProfile,onSources}:{profile:Profile;done:string[];available:boolean;onReviewProfile:()=>void;onSources:()=>void}){
const [messages,setMessages]=useState<Message[]>([]),[question,setQuestion]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
async function ask(e:React.FormEvent){e.preventDefault();if(busy||!question.trim())return;setBusy(true);setError('');const next=[...messages,{role:'user' as const,content:question.trim()}];try{let reply:string;if(available){const response=await fetch('/api/assistant',{method:'POST',signal:AbortSignal.timeout(60000),headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'chat',profile,done,messages:next.slice(-8).map(m=>({role:m.role,content:m.content.slice(0,3000)}))})});const data=await response.json() as {reply?:string;error?:string};if(!response.ok||!data.reply)throw Error(data.error||'Assistant could not respond. Retry.');reply=data.reply;}else reply=guidedReply(profile,done,question);setMessages([...next,{role:'assistant',content:reply,mode:available?'AI':'Guided planner'}]);setQuestion('');}catch(e){setError((e as Error).name==='TimeoutError'?'The AI request timed out. Your question is kept; retry.':(e as Error).message);}finally{setBusy(false);}}
return <section className="assistant-panel"><div className="section-heading"><div><span className="eyebrow">PERSONAL RELOCATION ASSISTANT</span><h2><Sparkles size={23}/> {profile.name?profile.name.split(' ')[0]+', let’s work through your move.':'Let’s work through your move.'}</h2><p>Your {profile.journey.toLowerCase()} profile and checklist provide the context.</p></div><span className="pill">{available?'Live OpenAI connection':'Guided planner · AI offline'}</span></div><div className="assistant-context"><strong>My context</strong><span>{profile.sector||'Add your interests in My profile'}</span><span>{profile.goals||'Add what you want to achieve'}</span></div>{!available&&<div className="feedback notice">You can ask about next steps, missing details, enquiry drafts and job searches now. Replies use curated rules, not GPT. Live AI is awaiting connection.</div>}<div className="chat-messages" aria-live="polite">{!messages.length&&<p className="muted">{available?'Ask about your move. Your profile and question are sent to OpenAI when you press Send.':'Choose a suggested question or type one below. Guided replies are generated locally from your roadmap.'}</p>}{messages.map((m,i)=><div className={'chat-message '+m.role} key={i}><strong>{m.role==='user'?'You':m.mode==='AI'?'Forever Abu Dhabi · AI':'Forever Abu Dhabi · Guided planner'}</strong><ReplyText text={m.content}/></div>)}</div><div className="question-chips">{['What should I prepare first?','What information is missing from my plan?','Draft an enquiry for my next step.',...(profile.journey==='Job seeker'?['Help me search for jobs.']:[])].map(q=><button key={q} onClick={()=>setQuestion(q)}>{q}</button>)}</div>{error&&<p role="alert" className="feedback error">{error}</p>}<form onSubmit={ask} className="assistant-input"><label className="sr-only" htmlFor="assistant-question">Your question</label><textarea id="assistant-question" maxLength={2000} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask about your Abu Dhabi move…" disabled={busy}/><button className="button primary" disabled={busy||!question.trim()}>{busy?<LoaderCircle className="spin" size={18}/>:<Send size={18}/>} {busy?'Thinking…':'Send'}</button></form><div className="loading-actions"><button className="button secondary" onClick={onReviewProfile}>Review my profile</button><button className="button secondary" onClick={onSources}>Explore official guidance</button></div><p className="field-help">No application is submitted. Chat stays in this visit. {available?'AI uses curated sources rather than live job listings.':'Guided mode has a limited set of supported questions.'}</p></section>;}
