import {z} from 'zod';
import {Profile,blankProfile,parseLabeledText} from './planner';
export const careerSchema=z.object({name:z.string().max(120),headline:z.string().max(160),skills:z.array(z.string().max(100)).max(20),experience:z.array(z.string().max(400)).max(8),education:z.array(z.string().max(300)).max(6),summary:z.string().max(1000),roles:z.array(z.object({title:z.string().max(100),reason:z.string().max(400)})).max(4),missing:z.array(z.string().max(200)).max(8),method:z.enum(['AI CV extraction','Labeled CV import'])});
export type Career=z.infer<typeof careerSchema>;
export function careerFromLabels(text:string):Career{const p=parseLabeledText(text,{...blankProfile,journey:'Job seeker'});const values=new Map<string,string>();for(const line of text.split('\n')){const index=line.indexOf(':');if(index>=0)values.set(line.slice(0,index).trim().toLowerCase(),line.slice(index+1).trim());}const list=(key:string,max:number)=>{const value=values.get(key)||'';return value?value.split(/[,;]/).map(s=>s.trim()).filter(Boolean).slice(0,max):[];};const skills=list('skills',20);const role=values.get('desired role')||values.get('role')||values.get('job title')||p.sector;return careerSchema.parse({name:p.name,headline:role,skills,experience:list('experience',8),education:list('education',6),summary:values.get('summary')||p.goals,roles:role?[{title:role,reason:'Your explicitly entered target role; not an AI recommendation.'}]:[],missing:[...(!p.name?['Your name']:[]),...(!role?['Desired role']:[]),...(!skills.length?['Skills']:[])],method:'Labeled CV import'});}
export function careerProfile(base:Profile,c:Career):Profile{return {...base,journey:'Job seeker',name:c.name||base.name,sector:c.headline||c.roles[0]?.title||c.skills.slice(0,5).join(', ')||base.sector,goals:c.summary||base.goals,evidenceReady:true};}
export function jobSearchLinks(role:string,location='Abu Dhabi'){const q=role.trim(),place=location.trim()||'Abu Dhabi';return {linkedin:'https://www.linkedin.com/jobs/search/?'+new URLSearchParams({keywords:q,location:place+', United Arab Emirates'}),indeed:'https://ae.indeed.com/jobs?'+new URLSearchParams({q,l:place})};}
export const careerSample='Name: Daniel Mensah\nDesired role: Data entry specialist\nSkills: Excel, typing, document management\nExperience: Data entry assistant — 2 years\nEducation: Diploma in business administration\nSummary: Find a data entry role in Abu Dhabi.';
export const cvJsonSchema={type:'object',additionalProperties:false,properties:{name:{type:'string'},headline:{type:'string'},skills:{type:'array',items:{type:'string'}},experience:{type:'array',items:{type:'string'}},education:{type:'array',items:{type:'string'}},summary:{type:'string'},roles:{type:'array',items:{type:'object',additionalProperties:false,properties:{title:{type:'string'},reason:{type:'string'}},required:['title','reason']}},missing:{type:'array',items:{type:'string'}}},required:['name','headline','skills','experience','education','summary','roles','missing']};
