import type {Journey} from './planner';
export type CityEvent={id:string;title:string;category:'Sport'|'Culture'|'Business';start:string;end:string;dateLabel:string;place:string;scope:'Abu Dhabi'|'Worldwide';organizer:string;description:string;url:string;tracks:Journey[]};
export const cityEvents:CityEvent[]=[
{id:'adif-london',title:'Abu Dhabi Investment Forum · London',category:'Business',start:'2026-10-15',end:'2026-10-15',dateLabel:'15 October 2026',place:'The Peninsula London, UK',scope:'Worldwide',organizer:'Abu Dhabi Investment Office',description:'An Abu Dhabi investment gathering in London. Register your interest with the organiser; attendance conditions apply.',url:'https://www.investwithabudhabi.com/en/home',tracks:['Investor','Founder']},
{id:'f1-2026',title:'Formula 1 Abu Dhabi Grand Prix',category:'Sport',start:'2026-12-04',end:'2026-12-06',dateLabel:'4–6 December 2026',place:'Yas Marina Circuit, Abu Dhabi',scope:'Abu Dhabi',organizer:'Formula 1',description:'The race weekend at Yas Marina. Check the organiser for tickets, session times and access conditions.',url:'https://www.formula1.com/en/racing/2026/united-arab-emirates',tracks:['Founder','Investor','Retiree','Job seeker']},
{id:'adfw-2026',title:'Abu Dhabi Finance Week',category:'Business',start:'2026-12-07',end:'2026-12-10',dateLabel:'7–10 December 2026',place:'Abu Dhabi · confirm venue with organiser',scope:'Abu Dhabi',organizer:'Abu Dhabi Finance Week',description:'A four-day finance gathering with programme and networking opportunities. Review pass conditions and the agenda before booking.',url:'https://www.adfw.com/event/2026/tickets',tracks:['Investor','Founder','Job seeker']},
{id:'marathon-2026',title:'ADNOC Abu Dhabi Marathon',category:'Sport',start:'2026-12-12',end:'2026-12-12',dateLabel:'12 December 2026',place:'Abu Dhabi City',scope:'Abu Dhabi',organizer:'Abu Dhabi Sports Council',description:'Explore the available race distances and registration requirements. Choose participation suitable for your circumstances.',url:'https://adsc.gov.ae/events/adnoc-abu-dhabi-marathon-2026/',tracks:['Founder','Investor','Retiree','Job seeker']}];
export function filterEvents(category:string,scope:string,savedOnly:boolean,saved:string[],journey?:Journey){return cityEvents.filter(e=>(category==='All'||e.category===category)&&(scope==='All locations'||e.scope===scope)&&(!savedOnly||saved.includes(e.id))&&(!journey||e.tracks.includes(journey))).sort((a,b)=>a.start.localeCompare(b.start));}
export function eventCalendar(e:CityEvent){const escape=(s:string)=>s.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');const end=new Date(e.end+'T12:00:00Z');end.setUTCDate(end.getUTCDate()+1);return ['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Forever Abu Dhabi//Events//EN','CALSCALE:GREGORIAN','BEGIN:VEVENT',`UID:${e.id}@ad-proactive`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}`,`DTSTART;VALUE=DATE:${e.start.replace(/-/g,'')}`,`DTEND;VALUE=DATE:${end.toISOString().slice(0,10).replace(/-/g,'')}`,`SUMMARY:${escape(e.title)}`,`LOCATION:${escape(e.place)}`,`DESCRIPTION:${escape(e.description+' Planning reminder only; no registration or ticket included. Confirm dates and times with organiser.')}`,`URL:${e.url}`,'END:VEVENT','END:VCALENDAR',''].join('\r\n');}
export const cityResources=[
{id:'culture',category:'Culture',title:'Art, heritage & everyday belonging',body:'Explore Louvre Abu Dhabi, Al Ain heritage and Emirati cultural experiences. Check opening hours and visitor guidance before you go.',source:'Experience Abu Dhabi',url:'https://visitabudhabi.ae/en/campaign/winter/arts-and-culture',action:'Explore cultural experiences',tracks:['Retiree','Founder','Investor','Job seeker']},
{id:'fitness',category:'Fitness',title:'Find your community through movement',body:'Browse the Abu Dhabi Sports Council calendar for sporting events. Registration, costs and participation conditions vary by event.',source:'Abu Dhabi Sports Council',url:'https://adsc.gov.ae/events',action:'Browse sports calendar',tracks:['Retiree','Founder','Investor','Job seeker']},
{id:'insurance',category:'Healthcare',title:'Understand healthcare & insurance',body:'Use the Department of Health guidance to compare coverage requirements, provider networks, exclusions and eligibility. An insurer confirms acceptance and the policy terms.',source:'Department of Health',url:'https://www.doh.gov.ae/en/faq?CategoryID=CBE886BBBBB44D2B9BE482D3980401FC',action:'Read insurance guidance',tracks:['Retiree','Founder','Investor','Job seeker']},
{id:'lifecare',category:'Healthcare',title:'Check Lifecare’s insurance partners',body:'Lifecare is a healthcare provider. Check its published partner list, then confirm whether your exact policy covers the facility and services you need.',source:'Lifecare Hospital',url:'https://lifecarehospital.ae/insurance/',action:'Check provider network',tracks:['Retiree','Founder','Investor','Job seeker']},
{id:'property',category:'Property',title:'Explore Abu Dhabi real estate information',body:'Use ADREC’s market-data portal to research areas and property information. This app does not calculate returns, value property or verify listings.',source:'Abu Dhabi Real Estate Centre',url:'https://adrec.gov.ae/en/market-data',action:'Open official property data',tracks:['Investor','Retiree','Founder','Job seeker']},
{id:'jobs',category:'Careers',title:'Explore roles in the startup ecosystem',body:'Search the Hub71 jobs board by role and location. Companies list opportunities in several countries; check that each role matches your intended location.',source:'Hub71 jobs board',url:'https://jobs.hub71.com/jobs',action:'Browse career opportunities',tracks:['Job seeker','Founder']},
{id:'invest',category:'Business',title:'Understand the investment ecosystem',body:'Explore Abu Dhabi Investment Office’s sectors and ecosystem resources. Programme conditions and investment decisions require your own review.',source:'Abu Dhabi Investment Office',url:'https://www.investwithabudhabi.com/en/home',action:'Explore the ecosystem',tracks:['Investor','Founder']},
{id:'markets',category:'Markets',title:'Follow Abu Dhabi’s listed companies',body:'Open ADX’s official equities page. Its public page labels data as delayed by 15 minutes; check the displayed timestamp and access conditions.',source:'Abu Dhabi Securities Exchange',url:'https://www.adx.ae/en/all-equities',action:'Open ADX market view',tracks:['Investor','Retiree','Founder','Job seeker']}];
