import {z} from 'zod';
import {Profile,sources,documentFields} from './planner';
export const firstWeekSchema=z.object({housingBudget:z.number().min(0).max(1000000).nullable(),done:z.array(z.enum(['prepare','land','settle'])).max(3)});
export type FirstWeek=z.infer<typeof firstWeekSchema>;
export const blankFirstWeek:FirstWeek={housingBudget:null,done:[]};
export const airportUrl='https://www.zayedinternationalairport.ae/en/parking-and-transport/taxis-car-rental/taxis-limousines';
export const welcomeUrl='https://visitabudhabi.ae/en/where-to-go/beaches/abu-dhabi-corniche';
export function firstWeekActions(p:Profile,housingBudget:number|null){return [
{id:'prepare' as const,when:'Before you fly',title:'Check entry requirements and pack your essentials',detail:`${p.passport?'You marked your passport copy ready.':'Prepare your passport copy.'} Confirm the entry and residency route for your circumstances with ICP. Keep travel documents and your first-night address accessible.${p.family>1?' Prepare the applicable family documents for your household of '+p.family+'.':''}`,checks:['Confirm entry requirements directly with ICP','Keep passport and travel documents accessible','Confirm your first-night booking and late check-in'],url:sources.find(s=>s.id==='residency')!.url,authority:'ICP'},
{id:'land' as const,when:'Arrival day',title:'Get from the airport to your first night',detail:'If arriving at Zayed International Airport, check the official taxi guidance. Save your accommodation address offline, confirm check-in, and allow time to rest before appointments.',checks:['Save the accommodation address and contact number','Check your airport transfer and luggage needs','Confirm how you will access maps and contact your host'],url:airportUrl,authority:'Zayed International Airport'},
{id:'settle' as const,when:'Days 2–7',title:'Compare housing and arrange your next conversations',detail:`${housingBudget===null?'Set a monthly housing budget before shortlisting.':'Your monthly housing limit is AED '+housingBudget.toLocaleString('en-GB')+'; this is your target, not a market rent estimate.'} Compare deposit, utilities, fees and commute separately. ${p.family>1?'Ask schools directly about places and admission requirements.':'Check travel time to work, meetings or community activities.'} Confirm insurance requirements and provider coverage.`,checks:['Compare total housing costs and contract terms','Check insurance requirements and provider coverage',p.journey==='Founder'?'Review Hub71 conditions and prepare a founder enquiry':p.journey==='Job seeker'?'Review your CV and search roles by location':p.journey==='Investor'?'Prepare questions for investment due diligence':'Prepare questions about residency and healthcare'],url:sources.find(s=>s.id==='housing')!.url,authority:'UAE Government'}];}
export function firstWeekPack(p:Profile,state:FirstWeek){const actions=firstWeekActions(p,state.housingBudget);return `# ${p.name||'Your'} — First week in Abu Dhabi\n\nArrival: ${p.arrival||'To confirm'}\nJourney: ${p.journey}\nHousehold: ${p.family}\nFocus: ${p.sector||'To confirm'}\nMonthly housing budget: ${state.housingBudget===null?'To confirm':'AED '+state.housingBudget.toLocaleString('en-GB')} (user target, not estimated rent)\n\n${actions.map(a=>`## ${state.done.includes(a.id)?'[x]':'[ ]'} ${a.when}: ${a.title}\n\n${a.detail}\n\n${a.checks.map(c=>'- '+c).join('\n')}\n\nOfficial guidance: ${a.url}`).join('\n\n')}\n\n## Document readiness\n\n${documentFields(p).map(d=>'- '+(d.ready?'[x]':'[ ]')+' '+d.label).join('\n')}\n\n## Make the city feel familiar\n\nExplore a Corniche walk if suitable for you; check conditions and visitor information before going. ${welcomeUrl}\n\n## Questions to confirm\n\n${!p.arrival?'- Arrival date\n':''}${state.housingBudget===null?'- Monthly housing budget\n':''}- Entry category and authority-specific documents\n- First-night booking, address and check-in\n- Actual rent, deposits, utilities and all fees\n- Insurance acceptance and coverage\n\nThis is a personal preparation checklist, not an eligibility decision or a booking. Completion is self-reported. Official links were checked on 2 October 2026; confirm current information at the source. No application or enquiry has been sent.\n`;}
