import { z } from 'zod';
export const journeys=['Founder','Investor','Retiree','Job seeker'] as const;
export type Journey=typeof journeys[number];
export const profileSchema=z.object({journey:z.enum(journeys).default('Founder'),evidenceReady:z.boolean().default(false),insuranceReady:z.boolean().default(false),name:z.string().max(120),company:z.string().max(120),sector:z.string().max(120),stage:z.enum(['Idea','Pre-seed','Seed','Series A','Later stage','Unknown']),arrival:z.string().refine(v=>{if(!v)return true;if(!/^\d{4}-\d{2}-\d{2}$/.test(v))return false;const d=new Date(v+'T12:00:00Z');return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===v;},'Use a valid YYYY-MM-DD date'),family:z.number().int().min(1).max(20),budget:z.number().min(0).max(1e9).nullable(),goals:z.string().max(2000),residency:z.enum(['Not arranged','Existing UAE residency','Unknown']),passport:z.boolean(),businessPlan:z.boolean(),pitchDeck:z.boolean(),familyDocuments:z.boolean()});
export type Profile=z.infer<typeof profileSchema>;
export const blankProfile:Profile={journey:'Founder',evidenceReady:false,insuranceReady:false,name:'',company:'',sector:'',stage:'Unknown',arrival:'',family:1,budget:null,goals:'',residency:'Unknown',passport:false,businessPlan:false,pitchDeck:false,familyDocuments:false};
export const sample:Profile={journey:'Founder',evidenceReady:false,insuranceReady:false,name:'Elena Rostova',company:'Northstar AI',sector:'AI / enterprise software',stage:'Seed',arrival:'2026-11-02',family:3,budget:120000,goals:'Establish a Middle East HQ, explore Hub71, and relocate with my partner and child.',residency:'Not arranged',passport:true,businessPlan:true,pitchDeck:false,familyDocuments:false};
export const sampleText='Name: Elena Rostova\nCompany: Northstar AI\nSector: AI / enterprise software\nStage: Seed\nArrival: 2026-11-02\nFamily size: 3\nSetup budget AED: 120000\nResidency: Not arranged\nGoals: Establish a Middle East HQ, explore Hub71, and relocate with my partner and child.\nPassport ready: yes\nBusiness plan ready: yes\nPitch deck ready: no\nFamily documents ready: no';
export const journeyDescriptions:Record<Journey,string>={Founder:'Launch and grow your business',Investor:'Explore capital and property opportunities',Retiree:'Prepare for a settled, connected life','Job seeker':'Prepare for your next career chapter'};
export function sampleForJourney(journey:Journey):Profile{if(journey==='Founder')return {...sample};return {...blankProfile,journey,name:journey==='Retiree'?'Michael Reed':journey==='Investor'?'Amira Hassan':'Daniel Mensah',sector:journey==='Retiree'?'Culture, wellbeing and an active community':journey==='Investor'?'Property and technology':'Product management / technology',family:journey==='Retiree'?2:1,arrival:'2026-12-01',budget:journey==='Investor'?250000:journey==='Retiree'?60000:25000,goals:journey==='Retiree'?'Understand residency, arrange healthcare and housing, and find cultural and fitness communities.':journey==='Investor'?'Research Abu Dhabi sectors and real estate information, and meet the investment ecosystem.':'Explore suitable roles, prepare my CV and confirm employment and relocation requirements.',passport:true,evidenceReady:false};}
export function documentFields(p:Profile):{key:keyof Profile;label:string;ready:boolean;detail:string}[]{return [{key:'passport',label:'Passport copy',ready:p.passport,detail:'For authority-specific document checks.'},...(p.journey==='Founder'?[{key:'businessPlan' as keyof Profile,label:'Business summary',ready:p.businessPlan,detail:'Activity, ownership and setup questions.'},{key:'pitchDeck' as keyof Profile,label:'Pitch deck',ready:p.pitchDeck,detail:'For programme enquiries where requested.'}]:[{key:'evidenceReady' as keyof Profile,label:p.journey==='Retiree'?'Retirement income / asset evidence':p.journey==='Investor'?'Investment due-diligence documents':'CV and qualifications summary',ready:p.evidenceReady,detail:'Confirm the final requirements with the relevant authority or provider.'}]),{key:'insuranceReady',label:'Health insurance requirements checked',ready:p.insuranceReady,detail:'Confirm eligibility, network and policy terms directly.'},...(p.family>1?[{key:'familyDocuments' as keyof Profile,label:'Family document checklist',ready:p.familyDocuments,detail:'Confirm the applicable category with ICP.'}]:[])];}
export const sources=[
{id:'hub71',name:'Hub71 Access Programme',authority:'Hub71',url:'https://www.hub71.com/program/access-programme',summary:'Review startup stage fit, founder relocation expectations, programme conditions and incentives. Selection is required; incentives are not automatic.',note:'Programme guidance reviewed 2 October 2026.'},
{id:'business',name:'Establish your business',authority:'Abu Dhabi DED',url:'https://added.gov.ae/en/set-up/establish-your-business',summary:'Business activity, legal form, trade name, approvals and premises are steps in establishing a business. Additional approvals depend on the activity.',note:'Official guidance reviewed 2 October 2026.'},
{id:'residency',name:'Issuing a residency permit',authority:'ICP',url:'https://icp.gov.ae/en/services-details/?serviceid=64afe3c1035448005bd52e64',summary:'Residence issuance is linked to an Emirates ID application. Documents, conditions and fees vary by category. Confirm your category through the official service.',note:'Official service reviewed 2 October 2026.'},
{id:'housing',name:'Leasing a property in the UAE',authority:'UAE Government',url:'https://u.ae/en/information-and-services/moving-to-the-uae/leasing-a-property-in-the-uae',summary:'Official guidance on renting and Abu Dhabi tenancy registration through Tawtheeq. Confirm requirements before signing.',note:'Official source located 2 October 2026. Check the live page for current requirements.'},
{id:'insurance',name:'Flexible health insurance guidance',authority:'Department of Health',url:'https://www.doh.gov.ae/en/faq?CategoryID=CBE886BBBBB44D2B9BE482D3980401FC',summary:'Compare policy requirements and benefits. Eligibility, acceptance and coverage need confirmation from the insurer.',note:'Official FAQ reviewed 2 October 2026.'},
{id:'property',name:'Abu Dhabi property market data',authority:'ADREC',url:'https://adrec.gov.ae/en/market-data',summary:'Official portal for researching property information. The prototype does not provide valuations or investment returns.',note:'Official portal reviewed 2 October 2026.'},
{id:'jobs',name:'Startup career opportunities',authority:'Hub71 jobs board',url:'https://jobs.hub71.com/jobs',summary:'Browse startup roles by skills and location. Confirm each role’s country and employer requirements.',note:'Jobs portal reviewed 2 October 2026.'},
{id:'employment',name:'Employment offers and contracts',authority:'MOHRE',url:'https://receipts.mohre.gov.ae/OfferInquiry/Index?langid=2',summary:'Official enquiry service for job offers and employment contracts. Use the relevant service for your circumstances.',note:'Official service reviewed 2 October 2026.'},
{id:'culture',name:'Culture and community discovery',authority:'Experience Abu Dhabi',url:'https://visitabudhabi.ae/en/campaign/winter/arts-and-culture',summary:'Explore cultural and heritage experiences as part of your relocation preparation.',note:'Official tourism guidance reviewed 2 October 2026.'},
{id:'investment',name:'Investment ecosystem',authority:'Abu Dhabi Investment Office',url:'https://www.investwithabudhabi.com/en/home',summary:'Explore sectors, ecosystem resources and investment events. Participation and programmes have their own conditions.',note:'Official ecosystem page reviewed 2 October 2026.'},
{id:'agriculture',name:'Agriculture investment enquiries',authority:'ADAFSA',url:'https://www.adafsa.gov.ae/en/investment/pages/investment-request.aspx',summary:'Contact the agricultural investment office to confirm project requirements and permissions.',note:'Official source located 2 October 2026; confirm current requirements directly.'}];
export type Task={id:string;title:string;detail:string;phase:number;category:string;source:string;requires:string[];missing:string[];offset:number;output:string};
export const phases=['Prepare your move','Establish your base','Connect & settle'];
export function buildPlan(p:Profile):Task[]{
const founder=p.journey==='Founder',retiree=p.journey==='Retiree',investor=p.journey==='Investor';
const evidenceLabel=retiree?'Retirement income / asset evidence':investor?'Investment due-diligence documents':'CV and qualifications summary';
const tasks:Task[]=[
{id:'profile',title:'Confirm your relocation brief',detail:'Review your chosen journey, priorities, arrival target and household needs.',phase:0,category:'Preparation',source:'residency',requires:[],missing:[!p.arrival&&'Arrival date',!p.name&&'Your name',!p.sector&&'Focus area / interests'].filter(Boolean) as string[],offset:-28,output:'Reviewed relocation profile'},
{id:'documents',title:founder?'Prepare your founder document pack':'Prepare your '+p.journey.toLowerCase()+' document pack',detail:'Collect your passport and supporting documents. The receiving authority or provider confirms the final requirements.',phase:0,category:'Documents',source:founder?'business':investor?'investment':retiree?'residency':'jobs',requires:['profile'],missing:[!p.passport&&'Passport copy',founder&&!p.businessPlan&&'Business summary',!founder&&!p.evidenceReady&&evidenceLabel].filter(Boolean) as string[],offset:-25,output:'Journey preparation pack'},
{id:'residency',title:p.residency==='Existing UAE residency'?'Check your existing residency arrangements':retiree?'Confirm retirement residency requirements':investor?'Explore appropriate investor residency routes':p.journey==='Job seeker'?'Confirm entry and employment residency requirements':'Confirm a residency route with ICP',detail:'Confirm the applicable category, evidence and requirements with ICP or the relevant authority. This prototype does not determine eligibility or promise approval.',phase:0,category:'Residency',source:'residency',requires:['documents'],missing:[],offset:-18,output:'Category-specific requirements'},
{id:'insurance',title:retiree?'Plan healthcare access and insurance':'Check your health insurance arrangements',detail:'Ask about eligibility, provider networks, exclusions and policy conditions for your household. For employment, confirm employer coverage. Do not assume a published programme applies to you.',phase:1,category:'Healthcare',source:'insurance',requires:['profile'],missing:[],offset:-12,output:'Insurance comparison questions'},
{id:'id',title:p.residency==='Existing UAE residency'?'Check Emirates ID details and validity':'Confirm residency and Emirates ID next steps',detail:'Confirm documents and appointments through the category-specific ICP service. Official approvals control the timeline.',phase:1,category:'Residency',source:'residency',requires:['residency'],missing:[],offset:1,output:'Appointment preparation checklist'},
{id:'housing',title:p.family>1?'Prepare a home shortlist for your household':'Prepare your housing requirements',detail:'Define location, budget, commute and household space. Confirm identification and tenancy registration arrangements before committing.',phase:1,category:'Housing',source:'housing',requires:['profile','residency'],missing:[],offset:3,output:'Housing requirements brief'},
{id:'community',title:retiree?'Build a culture and wellbeing shortlist':'Find your community in Abu Dhabi',detail:'Explore cultural experiences, sports calendars and events. Select activities that fit your interests, accessibility needs and schedule.',phase:2,category:'Community',source:'culture',requires:['profile'],missing:[],offset:7,output:'Community and events shortlist'}];
if(founder){tasks.push({id:'jurisdiction',title:'Compare business setup pathways',detail:'Compare mainland and free-zone requirements for your declared activity. Confirm legal form, approvals and premises with the licensing authority.',phase:0,category:'Business',source:'business',requires:['profile'],missing:[],offset:-21,output:'Jurisdiction comparison questions'},{id:'licensing',title:'Prepare your business setup enquiry',detail:'Prepare activity, legal form, approvals, premises and fee questions for the selected authority.',phase:1,category:'Business',source:'business',requires:['documents','jurisdiction'],missing:[],offset:-10,output:'Business enquiry draft'},{id:'hub71',title:'Prepare a Hub71 programme enquiry',detail:'Review programme fit, application timing and founder relocation expectations. Acceptance and incentives are not guaranteed.',phase:2,category:'Ecosystem',source:'hub71',requires:['profile'],missing:!p.pitchDeck?['Pitch deck']:[],offset:5,output:'Programme enquiry draft'});}
if(investor)tasks.push({id:'property-research',title:/property|real estate|housing/i.test(p.sector)?'Research the property market and ownership conditions':'Research your chosen investment sector',detail:'Use the relevant official sources; confirm ownership conditions, provider credentials, fees and project documents before proceeding. No returns are estimated here.',phase:1,category:'Investment',source:/property|real estate|housing/i.test(p.sector)?'property':'investment',requires:['documents'],missing:[],offset:-7,output:'Property due-diligence questions'},{id:'investor-network',title:'Explore the investment ecosystem and events',detail:'Review ADIO resources and organiser conditions for finance and investment gatherings. No deal access or investment match is guaranteed.',phase:2,category:'Ecosystem',source:'investment',requires:['profile'],missing:[],offset:5,output:'Investment ecosystem shortlist'});
if(retiree)tasks.push({id:'retirement-evidence',title:'Review your retirement evidence with ICP',detail:'Confirm the current category-specific age, income, asset and document requirements with ICP. No eligibility thresholds are inferred from your budget.',phase:0,category:'Retirement',source:'residency',requires:['documents'],missing:[],offset:-20,output:'Retirement enquiry draft'});
if(p.journey==='Job seeker')tasks.push({id:'career-search',title:'Shortlist roles aligned with your skills',detail:'Browse the Hub71 job board, filter by location and skills, and confirm each employer’s requirements. This app does not scrape listings or guarantee a match.',phase:0,category:'Careers',source:'jobs',requires:['documents'],missing:[],offset:-21,output:'Career search brief'},{id:'employment-check',title:'Verify offer and work authorisation steps',detail:'When an offer is received, use the appropriate MOHRE service and confirm the required work authorisation with the employer and relevant authority.',phase:1,category:'Employment',source:'employment',requires:['career-search'],missing:[],offset:-5,output:'Offer and work-authorisation checklist'});
if((founder||investor)&&/agri|farm|food|water/i.test(p.sector))tasks.push({id:'agriculture',title:'Prepare agricultural project due-diligence questions',detail:'Confirm land use, water, energy, permissions and project economics with the relevant authority. Agricultural construction permits are not available farm listings.',phase:1,category:'Agriculture',source:'agriculture',requires:['documents'],missing:[],offset:-5,output:'Agriculture feasibility enquiry'});
if(p.family>1)tasks.push({id:'family',title:'Prepare your family relocation questions',detail:'Confirm the applicable dependent category and its documents with ICP.',phase:2,category:'Family',source:'residency',requires:['residency'],missing:p.familyDocuments?[]:['Family document checklist'],offset:7,output:'Family preparation checklist'});
return tasks.sort((a,b)=>a.phase-b.phase||a.offset-b.offset);}
export function missingProfile(p:Profile){return [!p.name&&'Your name',!p.sector&&'Focus area / interests',!p.arrival&&'Arrival target',p.budget===null&&'Relocation budget',p.residency==='Unknown'&&'Residency status',...(p.journey==='Founder'?[!p.company&&'Company name',p.stage==='Unknown'&&'Startup stage']:[]),...documentFields(p).filter(d=>!d.ready).map(d=>d.label)].filter(Boolean) as string[];}
export function plannedDate(arrival:string,offset:number){if(!arrival)return 'Date to confirm';const d=new Date(arrival+'T12:00:00Z');if(Number.isNaN(d.getTime()))return 'Date to confirm';d.setUTCDate(d.getUTCDate()+offset);return d.toLocaleDateString('en-GB',{day:'numeric',month:'short',timeZone:'UTC'});}
export function taskStatus(t:Task,done:string[]){if(done.includes(t.id))return 'complete';if(t.missing.length)return 'missing';if(t.requires.some(id=>!done.includes(id)))return 'waiting';return 'ready';}
export function setTaskComplete(tasks:Task[],done:string[],id:string,complete:boolean){const task=tasks.find(t=>t.id===id);if(!task)throw Error('Task not found');if(complete){if(!['ready','complete'].includes(taskStatus(task,done)))throw Error('Complete prerequisites and confirm missing items first.');return [...new Set([...done,id])];}const removed=new Set([id]);let changed=true;while(changed){changed=false;for(const t of tasks)if(t.requires.some(r=>removed.has(r))&&!removed.has(t.id)){removed.add(t.id);changed=true;}}return done.filter(t=>!removed.has(t));}
export function parseLabeledText(text:string,base:Profile=blankProfile):Profile{const p={...base};const fields:Record<string,keyof Profile>={'summary':'goals','full name':'name','skills':'sector','desired role':'sector','role':'sector','job title':'sector','interests':'sector','household size':'family','budget':'budget','journey':'journey','evidence ready':'evidenceReady','insurance ready':'insuranceReady','name':'name','company':'company','sector':'sector','stage':'stage','arrival':'arrival','family size':'family','setup budget aed':'budget','goals':'goals','residency':'residency','passport ready':'passport','business plan ready':'businessPlan','pitch deck ready':'pitchDeck','family documents ready':'familyDocuments'};let found=0;for(const line of text.split(/\r?\n/)){const sep=line.indexOf(':');if(sep<0)continue;const k=fields[line.slice(0,sep).trim().replace(/^[•*\-]\s*/, '').replace(/\s+/g,' ').toLowerCase()];const v=line.slice(sep+1).trim();if(!k)continue;found++;if(['passport','businessPlan','pitchDeck','familyDocuments','evidenceReady','insuranceReady'].includes(k))(p as any)[k]=/^(yes|true)$/i.test(v);else if(k==='family'||k==='budget'){if(v&&Number.isFinite(Number(v.replace(/,/g,''))))(p as any)[k]=Number(v.replace(/,/g,''));}else (p as any)[k]=v;}const explicitRole=text.split(/\r?\n/).find(line=>/^\s*(desired role|job title|role)\s*:/i.test(line));if(explicitRole)p.sector=explicitRole.slice(explicitRole.indexOf(':')+1).trim();if(!found)throw Error('No labeled fields found. Enter Name: and Desired role: (one field per line), or use the labeled sample. Free prose requires AI.');const r=profileSchema.safeParse(p);if(!r.success)throw Error('Check the labeled values. Use the sample format or enter your profile manually.');return r.data;}
export function createPack(p:Profile,tasks:Task[],done:string[],mode:string,summary:string){return `# Forever Abu Dhabi — Relocation preparation pack\n\nGenerated: ${new Date().toISOString()}\nProcessing: ${mode}\nPreparation only. No government application has been submitted.\n\n## Relocation brief\n\nJourney: ${p.journey}\nName: ${p.name||'To confirm'}\nCompany: ${p.company||'To confirm'}\nActivity: ${p.sector||'To confirm'}\nStage: ${p.stage}\nArrival target: ${p.arrival||'To confirm'}\nHousehold: ${p.family}\nSetup budget: ${p.budget===null?'To confirm':'AED '+p.budget.toLocaleString('en-GB')} (user declared, not a fee estimate)\nResidency: ${p.residency}\nGoals: ${p.goals||'To confirm'}\n\n## Roadmap\n\n${summary}\n\nDates are planning targets, not official processing estimates.\n\n${tasks.map(t=>`### ${done.includes(t.id)?'[x]':'[ ]'} ${t.title}\n\nTarget: ${plannedDate(p.arrival,t.offset)}\nStatus: ${taskStatus(t,done)}\n${t.detail}\nOutput: ${t.output}\nPrerequisites: ${t.requires.map(id=>tasks.find(x=>x.id===id)?.title).join('; ')||'None'}\nMissing items: ${t.missing.join('; ')||'None identified'}\nSource: ${sources.find(s=>s.id===t.source)?.url}\n`).join('\n')}\n## Missing details\n\n${missingProfile(p).map(x=>'- '+x).join('\n')||'No gaps in profile fields. Confirm final authority requirements.'}\n\n## Journey enquiry draft\n\nI am preparing an Abu Dhabi relocation as a ${p.journey.toLowerCase()}. My focus is ${p.sector||'[focus]'}, my planned arrival is ${p.arrival||'[date]'}, and my household includes ${p.family} people. My goals are: ${p.goals||'[goals]'}. Please confirm applicable requirements, supporting documents, current fees and the next steps relevant to my circumstances.\n\n${p.journey==='Founder'?'## Business and programme enquiry draft\n\nMy company '+(p.company||'[company]')+' is at '+p.stage+' stage. Please confirm business activity requirements, licensing, premises and programme application conditions.':p.journey==='Investor'?'## Investment due-diligence questions\n\nPlease confirm ownership eligibility, provider credentials, title or instrument documents, all fees and applicable regulatory requirements. No investment commitment has been made.':p.journey==='Retiree'?'## Retirement and healthcare questions\n\nPlease confirm the current retirement category requirements, acceptable income or asset evidence, health insurance options and provider network.': '## Career and employment questions\n\nPlease confirm the role location, job requirements, offer verification and work-authorisation process. No offer or work permit is assumed.'}\n\n## Official sources\n\n${sources.map(s=>`- ${s.name}: ${s.url}\n  ${s.note}`).join('\n')}\n\nReview drafts before sending. This is not an official form or eligibility decision. Sources are not fetched live in rules-based mode.\n`;}
