const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),ts=require('typescript');
function load(path,imports){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:n=>{if(n in imports)return imports[n];throw Error(n)},Response,Request,URL,AbortSignal,performance,console});return exports;}
const zod=require('zod'),planner=load('lib/planner.ts',{zod}),agent=load('lib/relocation-agent.ts',{zod,'./planner':planner});
const call=(name,args,id)=>({type:'function_call',name,arguments:JSON.stringify(args),call_id:id});const final={type:'message',content:[{type:'output_text',text:JSON.stringify({summary:'Prepare your founder document pack and confirm current programme requirements. Your pitch deck is not yet ready.'})}]};
(async()=>{const requests=[],outputs=[call('lookup_curated_guidance',{topic:'hub71'},'call_1'),call('build_preparation_roadmap',{},'call_2'),call('draft_preparation_enquiry',{focus:'programme'},'call_3'),final];const fake=async(url,opts)=>{requests.push(JSON.parse(opts.body));return Response.json({status:'completed',output:[outputs.shift()]});};const result=await agent.runRelocationAgent(planner.sample,'test-only','test-model',fake);assert.equal(result.trace.length,3);assert(result.enquiry.includes('Northstar AI'));assert(result.enquiry.includes('programme'));assert.deepEqual(requests.map(r=>r.tool_choice),['required','required','required','none']);assert(requests.every(r=>r.store===false));const returned=requests[3].input.filter(i=>i.type==='function_call_output');assert.equal(returned.length,3);const graph=JSON.parse(returned[1].output);assert(graph.tasks.some(t=>t.id==='hub71'&&t.sourceUrl.includes('hub71.com')));assert(graph.tasks.some(t=>t.requires.length&&t.dependencyKind==='Suggested preparation order'));assert.equal(JSON.parse(returned[2].output).status,'Draft created; not sent');
await assert.rejects(()=>agent.runRelocationAgent(planner.sample,'test-only','test-model',async()=>Response.json({output:[final]})),/required tools/);
await assert.rejects(()=>agent.runRelocationAgent(planner.sample,'test-only','test-model',async()=>Response.json({output:[call('send_government_application',{},'bad')]})),/unsupported tool/);
await assert.rejects(()=>agent.runRelocationAgent(planner.sample,'test-only','test-model',async()=>Response.json({output:[call('lookup_curated_guidance',{topic:'invented'},'bad')]})));
await assert.rejects(()=>agent.runRelocationAgent(planner.sample,'test-only','test-model',async()=>Response.json({status:'incomplete',output:[]})),/incomplete/);
await assert.rejects(()=>agent.runRelocationAgent(planner.sample,'test-only','test-model',async()=>Response.json({output:[call('lookup_curated_guidance',{topic:'hub71'},'repeated')]})),/step limit/);
let user={userId:'alice'},env={OPENAI_API_KEY:'test-only'},remaining=[...requests.map((r,i)=>i===0?call('lookup_curated_guidance',{topic:'hub71'},'api_1'):i===1?call('build_preparation_roadmap',{},'api_2'):i===2?call('draft_preparation_enquiry',{focus:'programme'},'api_3'):final)];const integrated={runRelocationAgent:(p,k,m)=>agent.runRelocationAgent(p,k,m,async()=>Response.json({output:[remaining.shift()]}))};const api=load('app/api/assistant/route.ts',{'@/lib/relocation-agent':integrated,'@/app/chatgpt-auth':{getChatGPTUser:async()=>user},'@/lib/planner':planner,'cloudflare:workers':{env},zod});const req=()=>new Request('https://app.test/api/assistant',{method:'POST',headers:{origin:'https://app.test'},body:JSON.stringify({action:'plan',profile:planner.sample})});let response=await api.POST(req());assert.equal(response.status,200);assert.equal((await response.json()).trace.length,3);delete env.OPENAI_API_KEY;assert.equal((await api.POST(req())).status,503);user=null;assert.equal((await api.POST(req())).status,401);console.log('PASS: mocked Responses function-call loop, real tool outputs, validated arguments, bounded failure handling, no-key/auth rejection. No live model inference tested.');})().catch(e=>{console.error(e);process.exit(1)});
